#!/usr/bin/env bash

set -eu +x -o pipefail

# Install tools
echo "[ELI DOTFILES] (${USER:-UNSET} => ${HOME:-UNSET}) Installing tools..."
sudo apt update -y
sudo apt install -y \
  curl \
  wget \
  vim \
  jq \
  ripgrep \
  procps \
  shellcheck \
  exuberant-ctags \
  rbenv \
  htop \
  tree \
  iftop

echo "[ELI DOTFILES] (${USER:-UNSET} => ${HOME:-UNSET}) Installing tshark..."
echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
sudo apt-get install -y tshark

# install Golang
GO_VERSION=$(curl -q -sSL 'https://go.dev/VERSION?m=text' | grep go | sed -i 's/go//g')
rm -rf /usr/local/go && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz

# install rustup & Rust tools, LSP server
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
rustup component add rust-analyzer

# set up Git config
echo "[ELI DOTFILES] (${USER:-UNSET} => ${HOME:-UNSET}) Update Git config..."
git config  --replace-all user.email initialcontext@gmail.com
git config  --replace-all user.name initialcontext
git config  --replace-all github.user initialcontext

# Install config files
echo "[ELI DOTFILES] (${USER:-UNSET} => ${HOME:-UNSET}) Installing config files..."
DOTFILES_BASE="/workspaces/.codespaces/.persistedshare/dotfiles"
cp "$DOTFILES_BASE/dotfiles/vimrc" "$HOME/.vimrc"
cp "$DOTFILES_BASE/dotfiles/bashrc" "$HOME/.bashrc_eli"
echo "source $HOME/.bashrc_eli" >> "$HOME/.bashrc"

# Install Vim plugins
echo "[ELI DOTFILES] (${USER:-UNSET} => ${HOME:-UNSET}) Installing Vim plugins..."
mkdir -p "$HOME/.vim/pack/plugins/start"
mkdir -p "$HOME/.vim/pack/downloads/opt"

# install and bootstrap vim-go
git clone https://github.com/fatih/vim-go.git "$HOME/.vim/pack/plugins/start/vim-go"
vim +'GoInstallBinaries' +qa;

# install and bootstrap rust plugins and LSP client
git clone https://github.com/rust-lang/rust.vim "$HOME/.vim/pack/plugins/start/rust.vim"
git clone https://github.com/yegappan/lsp.git "$HOME/.vim/pack/downloads/opt/lsp"
vim -u NONE -c "helptags $HOME/.vim/pack/downloads/opt/lsp/doc" -c q

# install miscellaneous plugins
git clone https://github.com/scrooloose/nerdtree "$HOME/.vim/pack/plugins/start/nerdtree"
git clone https://github.com/ctrlpvim/ctrlp.vim.git "$HOME/.vim/pack/plugins/start/ctrlp.vim"
git clone https://github.com/vim-airline/vim-airline.git "$HOME/.vim/pack/plugins/start/vim-airline"
git clone https://github.com/chrisbra/unicode.vim.git "$HOME/.vim/pack/plugins/start/unicode.vim"

# Register SSH keys from GitHub
echo "[ELI DOTFILES]  (${USER:-UNSET} => ${HOME:-UNSET}) Installing authorized SSH keys..."
mkdir -p "$HOME/.ssh"
curl --silent --fail "https://github.com/initialcontext.keys" >> "$HOME/.ssh/authorized_keys"
